# Generated by Django 2.2.5 on 2019-10-30 04:57

from django.db import migrations, models
import django.db.models.deletion
import src.custom_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombrearticulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('eliminado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idcontacto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField()),
                ('activa', models.BooleanField()),
                ('eliminado', models.BooleanField()),
                ('fechasalida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('idkeyword', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', src.custom_types.EncryptedField(max_length=300)),
                ('primerapellido', src.custom_types.EncryptedField(max_length=300)),
                ('segundoapellido', src.custom_types.EncryptedField(blank=True, max_length=300, null=True)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idtipousuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=45)),
                ('email', src.custom_types.EncryptedField(max_length=300, unique=True)),
                ('passwd', src.custom_types.EncryptedField(max_length=300)),
                ('eliminado', models.BooleanField()),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='src.Persona')),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipousuario', to='src.Tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idstock', models.AutoField(primary_key=True, serialize=False)),
                ('articulos', models.ManyToManyField(blank=True, to='src.Articulo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='src.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idfoto', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=450)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='src.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('idestado', models.IntegerField(blank=True, null=True)),
                ('idmunicipio', models.IntegerField(blank=True, null=True)),
                ('idasentamiento', models.IntegerField(blank=True, null=True)),
                ('idcontacto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='src.Contacto')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='src.Usuario'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='src.Persona'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idcart', models.AutoField(primary_key=True, serialize=False)),
                ('articulos', models.ManyToManyField(blank=True, to='src.Articulo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='src.Cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(to='src.Categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='keywords',
            field=models.ManyToManyField(to='src.Keyword'),
        ),
    ]
